
"use client";

import React from 'react';
import ChecklistTable from '@/components/checklists/checklist-table';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { ListTodo } from 'lucide-react';

export default function ChecklistsPage() {
  return (
    <div className="space-y-6">
      {/* Banner and Clock are now inside ChecklistTable component */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <ListTodo className="h-6 w-6 text-accent" />
            Automated Task Checklists
          </CardTitle>
          <CardDescription>
            View and manage checklist items generated from recurring tasks. These items are populated by an automated Firebase Cloud Function.
          </CardDescription>
        </CardHeader>
        <CardContent>
          <ChecklistTable />
        </CardContent>
      </Card>
      <Card className="mt-6">
        <CardHeader>
            <CardTitle className="text-lg">About This Page</CardTitle>
        </CardHeader>
        <CardContent className="text-sm text-muted-foreground space-y-2">
            <p>This page displays checklist items dynamically generated by a daily Firebase Cloud Function based on your 'recurringTasks' Firestore collection.</p>
            <p>The Cloud Function (conceptually located at `firebase/functions/index.ts`) checks for tasks due today and creates corresponding entries in the 'checklists' Firestore collection.</p>
            <p>To make this fully operational:</p>
            <ul className="list-disc pl-5 space-y-1">
                <li>Ensure your Firebase project is set up and client-side configuration in `src/lib/firebase.ts` is correct (using your environment variables).</li>
                <li>Deploy the Firebase Cloud Function from `firebase/functions/index.ts` to your Firebase project and ensure it's scheduled to run daily.</li>
                <li>Seed the `recurringTasks` collection in Firestore (example in `firebase/firestore-seed/recurringTasks.json`).</li>
                <li>Set up appropriate Firestore security rules for the `recurringTasks` and `checklists` collections.</li>
            </ul>
        </CardContent>
      </Card>
    </div>
  );
}
