
"use client";

import React from 'react';
import ChecklistTable from '@/components/checklists/checklist-table';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { ListTodo } from 'lucide-react';

export default function ChecklistsPage() {
  return (
    <div className="space-y-6">
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <ListTodo className="h-6 w-6 text-accent" />
            Automated Task Checklists
          </CardTitle>
          <CardDescription>
            View and manage checklist items generated from recurring tasks. This is the operational heart of your daily compliance workflow.
          </CardDescription>
        </CardHeader>
        <CardContent>
          <ChecklistTable />
        </CardContent>
      </Card>
      <Card className="mt-6">
        <CardHeader>
            <CardTitle className="text-lg">About This Page</CardTitle>
        </CardHeader>
        <CardContent className="text-sm text-muted-foreground space-y-2">
            <p>This page displays checklist items dynamically generated by a scheduled process (e.g., a daily cron job) based on your 'recurringTasks' configuration.</p>
            <p>The backend process checks for tasks due today and creates corresponding entries in the 'checklists' collection, which are then displayed here for staff to complete.</p>
            <p>To make this fully operational:</p>
            <ul className="list-disc pl-5 space-y-1">
                <li>Ensure your database is set up with the correct tables/collections.</li>
                <li>Deploy a serverless function that reads your recurring tasks and creates daily checklist items.</li>
                <li>Seed the `recurringTasks` configuration with your facility's specific operational tasks.</li>
                <li>Set up appropriate database security rules for the `recurringTasks` and `checklists` collections.</li>
            </ul>
        </CardContent>
      </Card>
    </div>
  );
}
